### ISSUE TITLE
File custom name

### ISSUE THREAD

**Issue by dimaocheretko** [yii2tech/ar-file#10]
Hello! 
I cant find in documentation how to make base filenme, based not on ActiveRecord primary key.
For example, now for ActiveRecord Product with id 7127 I get filename /images/product/1/7/7127/7127_icon_15.png
But I need to make file name /images/product/1/7/7127/potato_icon_15.png
Potato, is the value from other field in Product model (or for example from related translations table)
Is there any option to do this?

**Comment by klimov-paul** [comment]
No, there is none.
