### ISSUE TITLE
`ImageFileBehavior` incorrect thumbnail when file has `tif` extension.

### ISSUE THREAD

**Issue by wao138** [yii2tech/ar-file#3]
When loaded image has `tif` extension, and in process need show result to user, like preview, in result we get incorrect image, 'cause browser don't support display `tif` images. Maybe need adding opportunity to change thumbnail extension?

**Comment by klimov-paul** [comment]
You may setup `transformCallback` to waht ever you like including extension change.
https://github.com/yii2tech/ar-file/blob/master/TransformFileBehavior.php#L58

**Comment by wao138** [comment]
When I use `transformCallback` I change only result name in `local` backed. But in `copy` process to storage we catch `Exception` that file is not found.

**Comment by klimov-paul** [comment]
Then you'll have to extend `TransformFileBehavior` handling different file extension.
This library has not been designed to support different file extensions for the same entity.

File transformations with different extensions can not be longer considered as same one.
If I were you I rather create a separated entity for the 'preview' file.

**Comment by klimov-paul** [comment]
Resolved by commit dddbd438111575176052962c12817be70afede0f
