### ISSUE TITLE
Change subDirTemplate

### ISSUE THREAD

**Issue by faenir** [yii2tech/ar-file#7]
Is it possible to use the php functions in `subDirTemplate`?
Something like this:
```php
'subDirTemplate' => date('Y', '{created_at}'),
```
Or how else can I configure `subDirTemplate` for path like this?
```php
'subDirTemplate' => "date('Y', {$model->created_at})/date('m', {$model->created_at})",
```
Also how I can change filename?

**Comment by klimov-paul** [comment]
> Is it possible to use the php functions in subDirTemplate?

No, this is not possible. However you can use any model attribute inside `subDirTemplate` pattern including virtual properties. Thus you can use following:

```php
'{created_at}/{created_at_year}/{created_at_month}'
```

declaring getters for `created_at_year` and `created_at_month` in your model:

```php
class MyAr extends \yii\db\ActiveRecord
{
    public function getCreated_at_year()
    {
        return date('Y', $this->created_at);
    }
}
```

> Also how I can change filename?

There is no native way for that. You can extend `FileBehavior` and make your own adjustments for it.
