### ISSUE TITLE
2 or more pictures saving

### ISSUE THREAD

**Issue by maxim-tishchenko** [yii2tech/ar-file#8]
How i can save 2 or more pictures in one model with this behavior?

**Comment by klimov-paul** [comment]
It is impossible. You should use several records in this case, e.g. item has many files.

**Comment by sheillendra** [comment]
public function behaviors() {
        return [
            \yii\behaviors\TimestampBehavior::class,
            \yii\behaviors\BlameableBehavior::class,
            [
                'class' => \yii2tech\ar\file\FileBehavior::class,
                'fileStorageBucket' => 'promo',
                'subDirTemplate' => 'id/{pk}',
                'fileAttribute' => 'image_id',
                'fileExtensionAttribute' => 'image_ext_id',
                'fileVersionAttribute' => 'image_ver_id',
            ],
            [
                'class' => \yii2tech\ar\file\FileBehavior::class,
                'fileStorageBucket' => 'promo',
                'subDirTemplate' => 'en/{pk}',
                'fileAttribute' => 'image_en',
                'fileExtensionAttribute' => 'image_ext_en',
                'fileVersionAttribute' => 'image_ver_en',
            ]
        ];
    }
```
